version: "3.7"

services:

  nautilus:
    build: .
    image: nautilus-chambers:latest
    restart: always
    ports:
      - 611:5000
      - 9191:9191

  mongo:
    image: mongo
    restart: always
