version: "3.7"
services:

  nautilus:
    build: .
    restart: always

  nginx:
    image: nginx
    depends_on:
      - nautilus
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
      - 443:443

  mongo:
    image: mongo
    restart: always
