version: "3.7"
services:

  nautilus:
    build: .
    restart: always

  nginx:
    image: nginx
    depends_on:
      - nautilus
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
      - 443:443

  letsencrypt:
    image: linuxserver/letsencrypt
    environment:
      - URL=lepto.tech
      - SUBDOMAINS=nautilus
      - ONLY_SUBDOMAINS=true
    volumes:
      - ./data/config:/config
    restart: unless-stopped

  mongo:
    image: mongo
    restart: always
    volumes:
      - ./data/db:/data/db
