version: "3.7"
services:

  nautilus:
    build: .
    restart: always

  nginx:
    image: nginx
    depends_on:
      - nautilus
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80

  letsencrypt:
    image: linuxserver/letsencrypt
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - URL=lepto.tech
      - SUBDOMAINS=nautilus
      - VALIDATION=http
      - ONLY_SUBDOMAINS=true
    volumes:
      - ./data/config:/config
    ports:
      - 443:443

  mongo:
    image: mongo
    restart: always
    volumes:
      - ./data/db:/data/db
